name: Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-mock streamlit pandas pytest-cov
        pip install -r requirements.txt
        
    - name: Create directories
      run: |
        if not exist "tests" mkdir tests
        if not exist "pages" mkdir pages
        
    - name: Run tests
      run: |
        echo "=================== Running Tests ==================="
        python -m pytest tests/test_budgets.py -vv --cov=pages --cov-report=term-missing --cov-report=xml --junitxml=test-results.xml
        
        echo ""
        echo "================= Coverage Summary ================="
        coverage report --format=text --show-missing
        
        echo ""
        echo "=================== Test Results ==================="
        python -c "import xml.etree.ElementTree as ET; tree = ET.parse('test-results.xml'); print(f'Total Tests: {tree.getroot().attrib.get("tests")}'); print(f'Failures: {tree.getroot().attrib.get("failures")}'); print(f'Errors: {tree.getroot().attrib.get("errors")}'); print(f'Skipped: {tree.getroot().attrib.get("skipped")}')"
      continue-on-error: true
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          coverage.xml
          .pytest_cache
        retention-days: 14
        if-no-files-found: warn

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: "test-results.xml"

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true