name: Python Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-mock streamlit pandas pytest-cov
        pip install -r requirements.txt
        
    - name: Create directories
      run: |
        if (-not (Test-Path "tests")) { New-Item -ItemType Directory -Path "tests" }
        if (-not (Test-Path "pages")) { New-Item -ItemType Directory -Path "pages" }
        
    - name: Run tests with detailed output
      run: |
        echo "=================== Running Tests ==================="
        python -m pytest tests/test_budgets.py -vv --cov=pages --cov-report=term-missing --cov-report=xml --junitxml=test-results.xml
        
        echo "`n================= Test Summary ==================="
        Get-Content test-results.xml | Select-String "testsuite" | ForEach-Object {
            $_ -match 'tests="(\d+)" failures="(\d+)" errors="(\d+)"' | Out-Null
            Write-Host "Total Tests: $($Matches[1])"
            Write-Host "Failures: $($Matches[2])"
            Write-Host "Errors: $($Matches[3])"
        }
        
        echo "`n================= Coverage Report ================"
        coverage report
      continue-on-error: true
        
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test Results
        path: test-results.xml
        reporter: java-junit
        fail-on-error: false

    - name: Generate Coverage Badge
      uses: tj-actions/coverage-badge-py@v2
      with:
        output: coverage.svg

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          test-results.xml
          coverage.xml
          .coverage
        retention-days: 14
        if-no-files-found: warn

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: "test-results.xml"

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true